# GitHub Actions Workflow
name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build & Push Backend
      run: |
        docker build -t pranaychatur/nnnewdjango-backend:latest ./backend
        docker push pranaychatur/nnnewdjango-backend:latest

    - name: Build & Push Frontend
      run: |
        docker build -t pranaychatur/nnnewreact-frontend:latest ./frontend
        docker push pranaychatur/nnnewreact-frontend:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /home/ubuntu

          # app git repo नसेल तर clean clone
          if [ ! -d app/.git ]; then
            rm -rf app
            git clone https://github.com/pranaychatur8975/newwwwww.git app
          else
            cd app
            git pull origin main
          fi

          cd /home/ubuntu/app
          ls -la   # debug: docker-compose.yml आहे का बघण्यासाठी

          docker-compose pull
          docker-compose up -d
